// Generated by CoffeeScript 1.7.1
(function() {
  var SkylineTracker;

  SkylineTracker = (function() {
    function SkylineTracker() {}

    SkylineTracker.prototype.api_endpoint = "http://localhost:3001/";

    SkylineTracker.prototype.project_key = null;

    SkylineTracker.prototype.api_key = null;

    SkylineTracker.prototype.request_token = null;

    SkylineTracker.prototype.initialized = false;

    SkylineTracker.prototype.init = function(project_key, api_key) {
      if (project_key === null || api_key === null) {
        return console.error("You havent provided either a project_key or an api_key");
      } else {
        this.project_key = project_key;
        this.api_key = api_key;
        this._setRequestToken();
        return this.initialized = true;
      }
    };

    SkylineTracker.prototype.track = function(guid, data) {
      var ajax, submissionData;
      if (data == null) {
        data = {};
      }
      if (!this.initialized) {
        throw new Error("Skyline not initialized");
      }
      submissionData = {
        guid: guid,
        data: data
      };
      ajax = this._generateXmlHttp();
      ajax.open("POST", "" + this.api_endpoint + "events/track");
      ajax.setRequestHeader("Content-Type", "application/json; charset=utf-8");
      ajax.setRequestHeader("Authorization", this.request_token);
      ajax.setRequestHeader("Access-Control-Allow-Origin", "*");
      return ajax.send(JSON.stringify(submissionData));
    };

    SkylineTracker.prototype._generateXmlHttp = function() {
      var xmlhttp;
      xmlhttp = null;
      if (window.XMLHttpRequest) {
        xmlhttp = new XMLHttpRequest();
      } else {
        xmlhttp = new ActiveXObject("Microsoft.XMLHTTP");
      }
      xmlhttp.onreadystatechange = (function(_this) {
        return function() {
          if (xmlhttp.readyState === 4) {
            if (xmlhttp.status !== 200 && xmlhttp.status !== 304) {
              return console.error("Skyline had a problem connecting. " + xmlhttp.status + " : " + (JSON.parse(xmlhttp.responseText).errors));
            }
          }
        };
      })(this);
      return xmlhttp;
    };

    SkylineTracker.prototype._setRequestToken = function() {
      return this.request_token = btoa(this.project_key + ":" + this.api_key);
    };

    return SkylineTracker;

  })();

  window.SkylineTracker || (window.SkylineTracker = new SkylineTracker());

}).call(this);
